m0_controller:
  ID: 0
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 0

m1_controller:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 0

m2_controller:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 0

m3_controller:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 3
  Profile_Acceleration: 0
  Profile_Velocity: 0

m4_controller:
  ID: 4
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  #Moving_Speed: 1023

m6_controller:
  ID: 6
  Return_Delay_Time: 0
  CW_Angle_Limit: 0
  CCW_Angle_Limit: 1023
  #Moving_Speed: 1023
